### ISSUE TITLE
Accessing the sqlite3 functions (e.g. get_autocommit)

### ISSUE THREAD

**Issue by szabgab** [stainless-steel/sqlite#100]
As I was debugging some code with transactions I found the need to call the [get_autocommit](https://sqlite.org/c3ref/get_autocommit.html) function. I did not find a way to do it with the current 0.36.1 version, but I managed to do it by adding
the following code to `src/connection.rs` and then using the locally patched version of the sqlite crate.

```rust
impl Connection {
    pub fn get_autocommit(&self) -> i32 {
        unsafe {
            ffi::sqlite3_get_autocommit(self.raw.0)
        }
    }
}
```

I wonder, is there already a way to call this function that I missed?

If not, would you like to add this, and maybe some of the other [functions](https://sqlite.org/c3ref/funclist.html) ? For a started I can send a PR adding this function.

As far as I understand #84 is also related to this as it is one of the functions.

**Comment by IvanUkhov** [comment]
Hello, I am not sure about exposing all the numerous low-level functions this way. Here is, however, a way to call them by means of `ffi` and `as_raw`. My hope is that it will be sufficient for less common cases.

https://github.com/stainless-steel/sqlite/blob/main/src/lib.rs#L91
https://github.com/stainless-steel/sqlite/blob/main/src/connection.rs#L87

**Comment by szabgab** [comment]
Thanks. With that I managed to write this: 

```rust
unsafe { sqlite::ffi::sqlite3_get_autocommit(connection.as_raw()) }
```
