### ISSUE TITLE
Insert statement with variable

### ISSUE THREAD

**Issue by hajsf** [stainless-steel/sqlite#13]
How can I use binding for data insertion, rather than data collection.

Something like:
```sql
"INSERT INTO person (name, time_created, data)
                  VALUES (?1, ?2, ?3)",
        me.name, me.time_created, me.data,
```

**Comment by IvanUkhov** [comment]
Do you get an error when using a prepared statement, as shown in the README?

**Comment by hajsf** [comment]
Did not try it yet.
