### ISSUE TITLE
cannot find -lsqlite3

### ISSUE THREAD

**Issue by hajsf** [stainless-steel/sqlite#14]
I'm using `macOS`, and trying to compile for `Android` using the command
```bash
cargo build --target x86_64-linux-android --release
```

I got the error:

> = note: /Users/../NDK/x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lsqlite3
> clang70: error: linker command failed with exit code 1 (use -v to see invocation)                        

I already have sqlite3 installed:
```bash
Hasans-Air:~ h_ajsf$ brew install sqlite
Warning: sqlite 3.26.0 is already installed and up-to-date
To reinstall 3.26.0, run `brew reinstall sqlite`
```

And it compiled smoothly for mac lib, using
```bash
cargo build --release
```

**Comment by IvanUkhov** [comment]
I think [this one](https://github.com/stainless-steel/sqlite3-src/issues/3) might be enough.

**Comment by hajsf** [comment]
Sorry, did not notice that both are for same author :)
