### ISSUE TITLE
if column is nullable and there are null values resulting values for those columns are always empty

### ISSUE THREAD

**Issue by NikosEfthias** [stainless-steel/sqlite#17]
I'd expect rows that contain data in  the specified column to return that and the others simply fail but all the rows fail during serialization for the specified column

```
                 CREATE TABLE IF NOT EXISTS current 
                 (user VARCHAR(50) ,
                 admin VARCHAR(50),
                 price FLOAT,
                 new_credit FLOAT,
                 card_id INT,
                 OP VARCHAR(10),
                 table_id VARCHAR(50),
                 game_id INT,
                 game_name VARCHAR(20),
                 winning_type varchar(20) not null default '',  #if theres no default here it fails the resulting rows are always empty during the serialization even if theres data
                 winning_amount float not null default 0.0,
                 op_time INT default (CURRENT_TIMESTAMP) )
```

**Comment by IvanUkhov** [comment]
Thank you for the issue. Can you please be more specific regarding which command fails and what the corresponding error message is?

**Comment by NikosEfthias** [comment]
thanks for the quick response.
```
select admin,price,new_credit,card_id,OP,table_id,game_id,game_name,winning_type,winning_amount,op_time,ROWID
        from current where user=? order by op_time desc
``` this is the exact command i write 
```
        while let Some(v) = cursor.next().unwrap(){
                res.push(UserAccountingData{
                    user           : user_id.to_string(),
                    admin          : v[0].as_string().unwrap_or("").to_string(),
                    price          : v[1].as_float().unwrap_or(0f64),
                    new_credit     : v[2].as_float().unwrap_or(0f64),
                    card_id        : v[3].as_integer().unwrap_or(0) as usize,
                    op             : v[4].as_string().unwrap_or("").to_string(),
                    table_id       : v[5].as_string().unwrap_or("").to_string(),
                    game_id        : v[6].as_integer().unwrap_or(0) as usize,
                    game_name      : v[7].as_string().unwrap_or("").to_string(),
                    winning_type   : v[8].as_string().unwrap_or("").to_string(),
                    winning_amount : v[9].as_float().unwrap_or(0f64),
                    op_time        : v[10].as_string().unwrap_or("").to_string(),
                    op_id          : v[11].as_integer().unwrap_or(0)
                })
        }
```
this is how i serialize data. 
if the `v[8]` and `v[9]` are mixed with `null` in rows all the rows returns null even if that particular row is not null quick solution for me was to assign a default value on table to get everything proper

**Comment by IvanUkhov** [comment]
Do you mean that all columns except for 8 and 9 are all right, and that you are able to iterate over all rows, but columns 8 and 9 always return `None` if any of the rows contains `NULL`?

**Comment by NikosEfthias** [comment]
yes exactly @IvanUkhov

**Comment by IvanUkhov** [comment]
I’ve gone through the code and haven’t found any obvious problems. Whenever the value is `NULL`, the raw type should be `SQLITE_NULL`, and `None` should be returned for that particular row and that particular column. It should be helpful to have a test for this scenario with a column containing missing values. I’d begin by extending `tests/lib.rs` with a small example.

**Comment by IvanUkhov** [comment]
Please have a look at the following test. Does it work for you?

```rust
#[test]
fn statement_read_null() {
    let connection = setup_users(":memory:");
    ok!(connection.execute("INSERT INTO users VALUES (2, 'Bob', NULL, NULL)"));
    let statement = "SELECT id, age FROM users";
    let statement = ok!(connection.prepare(statement));

    let mut count = 0;
    let mut cursor = statement.cursor();
    while let Some(row) = ok!(cursor.next()) {
        let id = row[0].as_integer().unwrap();
        if id == 1 {
            assert_eq!(row[1].as_float().unwrap(), 42.69);
        } else if id == 2 {
            assert_eq!(row[1].as_float().unwrap(), 0.0);
        } else {
            assert!(false);
        }
        count += 1;
    }
    assert_eq!(count, 2);
}
```

**Comment by IvanUkhov** [comment]
I think I have found the bug. It occurs when the first row returns `NULL`. Then the rest of the rows are assumed to be of this type without checking. Pushed a test for it.

**Comment by IvanUkhov** [comment]
It should be fixed now. Can you please try what’s on master and confirm that it works fine? I’ll then release a new version.

**Comment by NikosEfthias** [comment]
thanks, I will try as soon as possible today

**Comment by NikosEfthias** [comment]
It seems to be fixed now and i think this thread should be tagged as a bug rather than help wanted
