### ISSUE TITLE
cursor has a next method why doesnt it implement iterator ? 

### ISSUE THREAD

**Issue by NikosEfthias** [stainless-steel/sqlite#18]

**Comment by IvanUkhov** [comment]
The reason is that the interface is different than the one of `Iterator`. The method returns `Result`.

**Comment by kangalioo** [comment]
Is there information somewhere on how the Result<Option<_>> type should be handled? What does it represent; in what cases does it return Err and when does it return Ok(None)? This is essential to know in order to do robust and accurate error handling.

**Comment by IvanUkhov** [comment]
This package is a thin wrapper around the C API of SQLite. In this particular case, the behavior is described in relation to `sqlite3_step`:

https://www.sqlite.org/c3ref/step.html

**Comment by kangalioo** [comment]
Oh that was a quick response, thank you.
