### ISSUE TITLE
Is there support for close or specific error code checks?

### ISSUE THREAD

**Issue by Bergie1994** [stainless-steel/sqlite#23]
https://www.sqlite.org/c3ref/close.html

Also, is there any way to verify an error code. For example when calling open is there a way to verify the returned error is sqlite::Error::CANTOPEN for testing purposes?

**Comment by IvanUkhov** [comment]
Please take a look at this struct:

https://github.com/stainless-steel/sqlite/blob/master/src/lib.rs#L183

**Comment by Bergie1994** [comment]
Probably a noob question but why is this a separate create/repo?

**Comment by IvanUkhov** [comment]
It’s a good question. `sqlite` is based on `sqlite3-sys`; however, the error codes were not exposed here in any way, since there was no need for this.

**Comment by Bergie1994** [comment]
Gotcha. Thanks for the timely responses! One other question, I want to verify the number of rows removed via a query like "DELETE FROM a WHERE key = ?;"

Any suggestions? In the past I've directly used [sqlite3_changes](https://www.sqlite.org/c3ref/changes.html)

**Comment by IvanUkhov** [comment]
That function is not used. Then there is not such functionality at the moment.

**Comment by Bergie1994** [comment]
Gotcha. Any suggestion as to how I could locally add such behavior to my codebase?

**Comment by IvanUkhov** [comment]
Invoke this one

https://github.com/stainless-steel/sqlite/blob/master/src/statement.rs#L126

and then your function

https://github.com/stainless-steel/sqlite3-sys/blob/master/src/functions.rs#L48

**Comment by Bergie1994** [comment]
Thanks! Any existing examples?

**Comment by IvanUkhov** [comment]
Well, this package is full of them. It‘s exactly what it does: invocation of C functions.

**Comment by Bergie1994** [comment]
Sounds good I'll look through it (in hindsight that was an obvious answer), thanks for all the help!
