### ISSUE TITLE
Memory Leak While Opening Connection

### ISSUE THREAD

**Issue by smklein** [stainless-steel/sqlite#25]
Hey all, I believe there is a memory leak when opening a new connection fails:

https://github.com/stainless-steel/sqlite/blob/master/src/connection.rs#L28

The "ffi::sqlite3_open_v2" function returns immediately upon encountering an error (this is trivially reproducible with a file that does not exist). However, the correct behavior here is probably to invoke sqlite3_close() instead -- even on error.

From http://www.sqlite.org/c3ref/open.html:

"_Whether or not an error occurs when it is opened, resources associated with the database connection handle should be released by passing it to sqlite3_close() when it is no longer required._"

I have a build setup using clang's leak-sanitizer, and this was flagged - but even without this setup, calling the "Connection::open" function in a loop with a bad path should should a process with always-increasing memory consumption.

**Comment by IvanUkhov** [comment]
Thanks a lot! I’ll fix this when I find time, but please feel free to open a pull request.
