### ISSUE TITLE
sqlite::connection::Connection is private

### ISSUE THREAD

**Issue by nacika-ins** [stainless-steel/sqlite#4]
can not use `Connection` struct at public.
want to able to use.

```rust
use sqlite::connection::Connection;
```

```rust
struct Foo {
    conn: sqlite::connection::Connection
}
```

**Comment by nacika-ins** [comment]
I have learned from and after it public.
`use sqlite::Connection`

**Comment by IvanUkhov** [comment]
Thanks for the feedback! I’m glad that the problem is solved.


Regards,
Ivan
