### ISSUE TITLE
Page count

### ISSUE THREAD

**Issue by muteb** [stainless-steel/sqlite#43]
Hi,

I'm trying to use this cargo and exexute "SELECT page_count * page_size as size FROM pragma_page_count(), pragma_page_size();" and it return an empty although tested on python and it returns result. Just wondering if I'm doing it wrong or the lib doesn't supprt such query. 

```
fn check_size(){
    let connection = connectdb();
    let xx = connection.execute("SELECT page_count * page_size as size FROM pragma_page_count(), pragma_page_size();");
    println!("{:?}",xx);
    }
```

**Comment by IvanUkhov** [comment]
Hi, please take a look at the example on the front page. `execute` does not return the resulting rows; intead, it gives you an object to iterate over.

**Comment by muteb** [comment]
Thanks alot. it works like a charm.
