### ISSUE TITLE
Cursor.column_type always returns None

### ISSUE THREAD

**Issue by camertron** [stainless-steel/sqlite#55]
I'm having trouble getting column type information from `Cursor`s:

```rust
let db = sqlite::open("db.sqlite").unwrap();
let statement = db.prepare("select * from users;").unwrap();
let mut cursor = statement.into_iter();

while let Some(Ok(row)) = cursor.next() {
    for column_index in 0..cursor.column_count() {
        let column_type = cursor.column_type(column_index);
        println!("col type: {:?}", column_type);
    }
}
```

The `users` table contains two columns. `name` is a string, and `age` is an integer. Instead this code prints `None` for every column.

Any help is much appreciated!

**Comment by IvanUkhov** [comment]
Thank you for the issue! Hm, this is interesting. I added a test for this:

https://github.com/stainless-steel/sqlite/blob/main/tests/cursor.rs#L37-L59

That is weird is that is start to return `Type::Null` on the fifth row (six rows in total):

https://github.com/stainless-steel/sqlite/actions/runs/3530767381/jobs/5923127711
