### ISSUE TITLE
open a .db or .sqlite file

### ISSUE THREAD

**Issue by cyberpunkbln** [stainless-steel/sqlite#58]
Hello,
stupid question, but how i can load a simple sqlite-file?

i take a string or an Path and give this the open function, but he allways returns is_ok()->true, even the file not exists?
And tables he found not, if it exists or not.

thx

**Comment by IvanUkhov** [comment]
When it comes to `open`, it “open a read-write connection to a new or existing database.”

https://docs.rs/sqlite/latest/sqlite/struct.Connection.html

This means that the file is created if it does not exist. If you would like a different behavior, try `open_with_flags`.

**Comment by cyberpunkbln** [comment]
@IvanUkhov sry i have found my own failure, was the wrong firefox profile cookies.sqlite.
