### ISSUE TITLE
Implementing From for Option and bool on Value

### ISSUE THREAD

**Issue by Colonial-Dev** [stainless-steel/sqlite#61]
Hey there! I'm a big fan of this crate (much simpler and cleaner than `rusqlite`), and I was wondering if you'd be interested in a PR implementing `From<Option<T>>` (where `T: Into<Value>`) and `From<bool>` for `Value`, as well as their `TryFrom` inverses.

I've already been using these semantics in some free helper functions:
- If an `Option<T>` holds a `Some(T)`, perform the appropriate conversion into a `Value` on the `T`.  If it holds `None`, instead yield a `Value::Null`.
- `false` becomes `Value::Integer(0)` and `true` becomes `Value::Integer(1)` (as [recommended](https://www.sqlite.org/datatype3.html) by the SQLite devs.)

What do you think?

**Comment by IvanUkhov** [comment]
Hello! Yes, some `Option` cases are implemented, and some are missing. I currently cannot recall what the reason was, but if you have time, it would be nice to have indeed. Regarding the second bullet point, yes, it might be good to have too, but let us treat it as two different PRs. Thank you!

**Comment by SomewhereOutInSpace** [comment]
Awesome, I'll take a crack at it next week once I'm back at school!
