### ISSUE TITLE
Possible UB - Vec created with uninit values

### ISSUE THREAD

**Issue by SomewhereOutInSpace** [stainless-steel/sqlite#64]
While working on #61, I found that `clippy` was very displeased by [the implementation of `ReadableWithIndex` for `Vec<u8>`](https://github.com/stainless-steel/sqlite/blob/668a43524fdb641eadae8b4f9328fe31ead1e1af/src/statement.rs#L559-L560):

```
error: calling `set_len()` immediately after reserving a buffer creates uninitialized values
   --> src/statement.rs:559:13
    |
559 |             let mut buffer = Vec::with_capacity(count);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
560 |             buffer.set_len(count);
    |             ^^^^^^^^^^^^^^^^^^^^^
    |
    = help: initialize the buffer or wrap the content in `MaybeUninit`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec
    = note: `#[deny(clippy::uninit_vec)]` on by default
```
Looking at how the buffer is used, I doubt it's an actual problem (it's immediately written into with `ptr::copy_nonoverlapping`, thus initializing it) *but* I am not well versed in the arts of `unsafe` and clippy considers this bad enough to warrant making it a `deny` lint, so I figured it would be worth reporting.

The [Clippy site](https://rust-lang.github.io/rust-clippy/master/#uninit_vec) suggests using `MaybeUninit`.

**Comment by IvanUkhov** [comment]
Hi, after re-reading the documentation, I see new that there is a violation that the length should be set _after_ initializing the elements. I have swapped lines 560 and 561. I have also addressed all lints by Clippy and added a check to the workflow. Thank you!
