### ISSUE TITLE
Panics when row.read/try_read are called with a non-existent column

### ISSUE THREAD

**Issue by gtklocker** [stainless-steel/sqlite#67]
Simple example:
```rust
    #[test]
    fn it_does_not_panic() {
        let conn = sqlite::open(":memory:").unwrap();
        conn.execute("create table tbl (x, y)").unwrap();
        conn.execute("insert into tbl (x, y) values (42, 43)")
            .unwrap();
        let st = conn.prepare("select x, y from tbl").unwrap();
        for row in st.into_iter().map(|row| row.unwrap()) {
            row.try_read::<i64, _>("z"); // <--- this will panic
        }
    }
```

Output:
```
thread 'cached_rpc::test::it_does_not_panic' panicked at 'the index is out of range', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlite-0.30.4/src/cursor.rs:172:9
```

Does a safer read method exist? This might be a deliberate design decision, but regardless it would be good to think about offering a safer interface.

**Comment by IvanUkhov** [comment]
Hello! Yes, it is by design. It is similar to accessing an out-of-range element of a vector. There is a function to check what columns exists: `column_names`. However, perhaps `column_mapping` would be more efficient for your use case.

**Comment by EvanCarroll** [comment]
@IvanUkhov I don't think this is a good design decision. `try_read` should not panic by design. The very nature of calling it `try` and returning a Result is so that it doesn't panic. It doesn't make sense to panic if the column doesn't exist. It would be substantially better to just return the error ColumnIndexInvalid or something.

**Comment by EvanCarroll** [comment]
This problem doesn't exist on `rusqlite`, with that I get,

```
thread 'main' panicked at src/main.rs:144:80:
called `Result::unwrap()` on an `Err` value: RuSqlite(InvalidColumnName("is_Secure"))
```

However, with stainless-steel/sqlite, I get

```
thread 'main' panicked at /home/ecarroll/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlite-0.31.1/src/cursor.rs:172:9:
the index is out of range
stack backtrace:
```

Major major difference in my opinion. One of them has `InvalidColumnName` error and tells me exactly what the error is. Beautiful.
