### ISSUE TITLE
When using sqlite-src, shared cached memory creates a file

### ISSUE THREAD

**Issue by jdmichaud** [stainless-steel/sqlite#68]
When running this MVE:
```rust
use std::error::Error;
use sqlite::Connection;

fn main() -> Result<(), Box<dyn Error>> {
  let dbname = "file::memory:?cache=shared";
  let connection = Connection::open(dbname)?;
  Ok(())
}
```
Without the `sqlite3-src` package in `Cargo.toml` all is well. But if I add to my dependencies:
```toml
sqlite3-src = { version = "0.4", features = ["bundled"] }
```
## Observed outcome:
Running the same code will create `file::memory:?cache=shared` as a file instead as using it as a memory DB.

## Expected outcome:
Do not create any file but rely on a memory DB whose cache is shared as detailed [here](https://www.sqlite.org/inmemorydb.html#sharedmemdb).

**Comment by IvanUkhov** [comment]
Hello, this is a thin wrapper around SQLite. The crate does not create any files by itself. The one thing I can come up with is the default open flags:

https://github.com/stainless-steel/sqlite/blob/main/src/connection.rs#L29

I close this, but can you please try with `with_open_flags` and see if it persists?
