### ISSUE TITLE
Upsert query fails (only in Docker)

### ISSUE THREAD

**Issue by leana8959** [stainless-steel/sqlite#70]
Hello,

I recently discovered this problem. To better illustrate the problem, I created a repo of a minimal reproduction of the problem I found.

TL;DR: Using upsert inside Docker would fail. I have tried to compile SQLite from source too.

Here's the [repo](https://github.com/leana8959/rust_sqlite_repr) I mentioned earlier.

Thank you and have a nice day :)

**Comment by leana8959** [comment]
Hello, thank you for your prompt reply!

> The version that is shipped with this crate is 3.39.2 in accordance with this crate:

Does that mean I should also install sqlite of version 3.39.2?

> According to the documentation, UPSERT should be available starting from 3.24.0:

In the docker container, I tried both installing sqlite from apt (3.34.1-3) and from source (3.42). These two version are both more recent than 3.24.0, hence my confusion.

**Comment by IvanUkhov** [comment]
Well, the crate compiles its own version of SQLite (I have just updated it to 3.42.0). You do not need to install anything manually. If you say it works outside of the container but does not work inside, it indicates that the linking happens differently. Please try with the latest version, which I released a few minutes ago, and try without installing anything in the container.

**Comment by leana8959** [comment]
> You do not need to install anything manually.

I didn't know this, thank you for letting me know.

> Please try with the latest version, which I released a few minutes ago, and try without installing anything in the container.

Thank you for reacting promptly! I just tried updating the crate in my error repr repo and the problem seems to persist.

```sh
rust_sqlite_repr-myapp-1  |    Compiling sqlite3-sys v0.15.0
rust_sqlite_repr-myapp-1  |    Compiling sqlite v0.30.5
rust_sqlite_repr-myapp-1  |    Compiling rust_sqlite_repr v0.1.0 (/usr/src/myapp)
...
rust_sqlite_repr-myapp-1  | running 2 tests
rust_sqlite_repr-myapp-1  | test upsert_test ... FAILED
rust_sqlite_repr-myapp-1  | test basic_test ... ok
rust_sqlite_repr-myapp-1  |
rust_sqlite_repr-myapp-1  | failures:
rust_sqlite_repr-myapp-1  |
rust_sqlite_repr-myapp-1  | ---- upsert_test stdout ----
rust_sqlite_repr-myapp-1  | thread 'upsert_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Some(1), message: Some("near \"UPDATE\": syntax error") }', src/main.rs:40:10
```

This is the error that I dealt with in the beginning.

**Comment by leana8959** [comment]
I just did this to be sure, and there's indeed no existing sqlite3 that it can bind to. This should guarantee that my program is linked to the SQLite provided by the crate right?
```sh
$ docker run -it --rm rust:1.70 bash
root@f72a727011d1:/# sqlite3 --version
bash: sqlite3: command not found
```

However, I did discover something fascinating. I'm not sure if it's related though.
I tried to install SQLite from `apt` (3.34.1) and from source (3.42.0). These two versions are both more recent than 3.24.0, the minimum version for SQLite upsert to work. The binary installed from `apt` gives the same error earlier, while the one from source doesn't.

Here's the output using `apt` (3.34.1) (error)
```sh
root@54b07f08ca32:/# apt-get update && apt-get install -y sqlite3
...
root@54b07f08ca32:/# sqlite3
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE users(name TEXT, age INTEGER, PRIMARY KEY (name));
sqlite> INSERT INTO users (name, age)
VALUES('jean', 49)
ON CONFLICT DO UPDATE SET age=49;
Error: near "UPDATE": syntax error
``` 

Here's the output compiling from source (3.42.0) (working)
```sh
root@3555a4ca62d2:/# cd /tmp && \ 
    wget https://www.sqlite.org/2023/sqlite-autoconf-3420000.tar.gz && \
    tar xfz sqlite-autoconf-3420000.tar.gz && \
    cd sqlite-autoconf-3420000 && \
    ./configure && make && make install
...
root@3555a4ca62d2:/tmp/sqlite-autoconf-3420000# sqlite3
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE users(name TEXT, age INTEGER, PRIMARY KEY (name));
sqlite> INSERT INTO users (name, age)
VALUES('jean', 49)
ON CONFLICT DO UPDATE SET age=49;
```

However, I'm not sure how this relates to the issue I'm having, since there's no SQLite preinstalled in the image `rust:1.70`. The weird thing is that 3.34.1 is more recent than 3.24.0, yet it fails on that specific upsert query.

Thank you :)

**Comment by IvanUkhov** [comment]
The last listing shows that `sqlite3` itself cannot handle that query. So this issue is not so much about this crate but about how one uses SQLite. Have you even seen this query working?

**Comment by leana8959** [comment]
I'm not sure that you understood, the last query worked (it didn't show syntax error), which was compiled from source. So yes, I have seen it working.

**Comment by leana8959** [comment]
> Sorry. I misread the output.

I see. It's okay, I hope I wasn't too harsh too. Thank you for your help.

> Try something like this in the container:

There's indeed some library with the command you mentioned. I think this is why!
```sh
root@eb258c0927e1:/# find / -name '*sqlite*' 2> /dev/null
/usr/include/sqlite3.h
/usr/include/sqlite3ext.h
/usr/lib/aarch64-linux-gnu/libsqlite3.a
/usr/lib/aarch64-linux-gnu/libsqlite3.so
/usr/lib/aarch64-linux-gnu/pkgconfig/sqlite3.pc
/usr/lib/aarch64-linux-gnu/libsqlite3.so.0
/usr/lib/aarch64-linux-gnu/libsqlite3.so.0.8.6
/usr/lib/python3.9/lib-dynload/_sqlite3.cpython-39-aarch64-linux-gnu.so
/usr/lib/python3.9/sqlite3
/usr/lib/python3/dist-packages/hgext/__pycache__/sqlitestore.cpython-39.pyc
/usr/lib/python3/dist-packages/hgext/sqlitestore.py
/usr/share/doc/libsqlite3-dev
/usr/share/doc/libsqlite3-0
/usr/share/mime/application/vnd.sqlite3.xml
/usr/share/mime/application/x-kexiproject-sqlite2.xml
/usr/share/mime/application/x-kexiproject-sqlite3.xml
/usr/share/mime/application/x-sqlite2.xml
/var/lib/dpkg/info/libsqlite3-dev:arm64.list
/var/lib/dpkg/info/libsqlite3-dev:arm64.md5sums
/var/lib/dpkg/info/libsqlite3-0:arm64.list
/var/lib/dpkg/info/libsqlite3-0:arm64.md5sums
/var/lib/dpkg/info/libsqlite3-0:arm64.shlibs
/var/lib/dpkg/info/libsqlite3-0:arm64.symbols
/var/lib/dpkg/info/libsqlite3-0:arm64.triggers
```
With this said, how can I force my program to *not* link to this version in the container that doesn't work? How does the linker choose which one to link?

Thanks :)

**Comment by IvanUkhov** [comment]
Please add `sqlite3-sys` into the dependencies and activate this feature:

https://github.com/stainless-steel/sqlite3-src/blob/main/Cargo.toml#LL20C1-L20C8

**Comment by IvanUkhov** [comment]
I misspelled. I meant `sqlite3-src`.

**Comment by leana8959** [comment]
Ah ha!
Hurray! It worked! Thank you so much!
