### ISSUE TITLE
Provide a method to consume values in rows

### ISSUE THREAD

**Issue by EvanCarroll** [stainless-steel/sqlite#76]
Inspired by this problem https://stackoverflow.com/q/77235264/124486

----

Currently you can't call,

    row.read::<Vec<u8>, _>(col).into()

Because a `Row` must own the `Vec<Values>` and a `Value` must own the data. I would propose making a newtype of `Option<>` like  `MaybeRead<>` and making a `Row` a `Vec<MaybeRead<Value>>` this would allow you to call something like,

    row.read_owned::<Vec<u8>, _>(col).into()

Where could `read_owned` replace the `Some(Value)` in the `MaybeRead<Value>` with None using `std::mem::take` providing the owned type.  The largest use case of selecting from a database is to move the data from this library into native Rust structs that represent that data. I feel this library's API falls short of making this reasonable and easy for this use case.

**Comment by IvanUkhov** [comment]
I think it can be solved by getting the value vector out of the row and decomposing it:

```rust
let values: Vec<Value> = row.into();
let value: Vec<u8> = values[0].try_into()?;
```

**Comment by EvanCarroll** [comment]
If I do that I've decomposed the row and I can't index it by column name. That's not solving the problem. That's creating a new problem.

**Comment by IvanUkhov** [comment]
The column mapping is available via `cursor.column_mapping()`. Would that work for you?

**Comment by V0ldek** [comment]
It is a workaround, but it'd make for a nicer API to have something like `get<T, U>(self, column: U) -> Value where U: RowIndex` (and a sister `try_get`).

The `Row` is already holding a reference to the column mapping, it can support this operation standalone, without needing to involve a cursor.

**Comment by IvanUkhov** [comment]
I added `Row::take` here:

https://github.com/stainless-steel/sqlite/commit/629601d6269b9bb3c7117e4beabfce6ccd248e30

However, it is not the API you want: it returns a `Value` instead of the underlying type. It is because it does not feel right to do the conversion from `Value` to the target type in the same function, as it would lose the value when the conversion fails.
