### ISSUE TITLE
Support for SQLITE_IOCAP_IMMUTABLE,

### ISSUE THREAD

**Issue by EvanCarroll** [stainless-steel/sqlite#78]
I would like to open a SQL Lite database in read-only immutable mode to bypass the lock that stops me from reading it. I don't see this supported but it sounds very useful.

https://www.sqlite.org/c3ref/open.html
https://stackoverflow.com/a/69574421/124486

**Comment by EvanCarroll** [comment]
It seems there is a READONLY flag supported but the IMMUTABLE flag is not supported. The Immutable flag is the one that ignores the lock.

**Comment by IvanUkhov** [comment]
Hello, thank you! I will add support for URIs.
