### ISSUE TITLE
Why does this module exist?

### ISSUE THREAD

**Issue by EvanCarroll** [stainless-steel/sqlite#79]
This isn't an insult but why does this module exists? What's the reason you started to create it? I migrated my code base to rusqlite, and I noticed no more panics -- this issue doesn't exist, https://github.com/stainless-steel/sqlite/issues/67

Moreoever, this other issue about reading into a Vec<u8> also doesn't exist in rusqlite,

```
-pub fn read_vecu8( row: &sqlite::Row, col: &str ) -> Vec<u8> {
-       row[col].clone().try_into().unwrap()
+pub fn read_vecu8( row: &rusqlite::Row, col: &str ) -> Result<Vec<u8>, CookieError> {
+       let val: Vec<u8> = row.get(col)?;
+       Ok( val )
 }
````

You can see `row[col].clone().try_into().unwrap()` goes away and just becomes `let val: Vec<u8> = row.get(col)?;` https://github.com/stainless-steel/sqlite/issues/76

Not saying this is a bad module, I just don't understand how it's different from rusqlite

**Comment by IvanUkhov** [comment]
Hello, I am sorry for the trouble this package gave you. Indeed, `rusqlite` is an excellent alternative.
