### ISSUE TITLE
Extension loading?

### ISSUE THREAD

**Issue by donaldcallen** [stainless-steel/sqlite#8]
It appears to me that you provide no way to enable extension loading. Trying to call sqlite3_sys::sqlite3_enable_load_extension myself, I find that the raw field of the Connection struct is private. I have an application for which I need to load the math extensions provided by sqlite. Perhaps I have overlooked something. Do you have any suggestions for accomplishing this or do I need to switch to rusqlite, which does provide a mechanism for enabling and loading extensions.

**Comment by IvanUkhov** [comment]
Thanks for the issue! I can’t think of a way to achieve it here without changing the code. Theoretically, one could add `as_raw` to `Connection`, but then one should be consistent and implement it for `Statement` as well. If you like, feel free to open a pull request.

**Comment by IvanUkhov** [comment]
Added `as_raw` in v0.23.8.
