### ISSUE TITLE
Error messages for incorrect queries could be improved

### ISSUE THREAD

**Issue by officiallyaninja** [stainless-steel/sqlite#82]
Consider the following (wrong) insert statement (
```rust
use sqlite::Connection;

fn main() {
    let conn = Connection::open("data.db").unwrap();
    //let _ = conn.execute("CREATE TABLE test(number INTEGER, name TEXT)");
    match conn.execute("INSERT INTO test(field) VALUES(1 \"text\")") {
        Ok(_) => {}
        Err(e) => {
            println!("{e}")
        }
    };
}
```

The error you get is 
```
near ""text"": syntax error (code 1)
```

Which is a pretty confusing error message, Not too bad here but when you're formatting arguments it can be pretty bad

Ideally the error message should look something like this
```
INSERT INTO test(field) VALUES(1 "text")
                                 ^^^^^^ <- error near ""text"": syntax error (code 1)
```

Ideally if possible it should show the source code from which the query originated but I have no idea if that's possible

**Comment by IvanUkhov** [comment]
Hello, yes, indeed. However, it is not part of this crate. It comes from the C code, and here it is only a thin wrapper propagating whatever is returned.
