### ISSUE TITLE
Statement hangs up wiht UPSERT clause on Windows

### ISSUE THREAD

**Issue by leirn** [stainless-steel/sqlite#85]
Using sqlite version 0.32.0
Windows 11
rustc 1.75.0

I am trying to prepare a statement with an ```UPSERT``` clause in it. Connection.prepare(Statement); hangs up and never returns. 

```rust
let connection = sqlite::open(":memory:").expect(ERROR_SQLITE_ACCESS);
let query = "UPSERT INTO data_last_update (file, sha, date) VALUES (?, ?, unixepoch())";
let mut statement = connection .prepare(query)?;
println!("Here");
```
The ```println!``` is never reached.
If I replace ```UPSERT``` with ```INSERT```, everything works fine.

There are no version of SQLite installed on the computer.

I also read #70 and tried to apply ```sqlite3-sys``` or ```sqlite3-src``` with no success.

**Comment by IvanUkhov** [comment]
Hello, I think it is unrelated to this crate. It is likely due to SQLite itself. You have tried with `bundled`, right?

**Comment by IvanUkhov** [comment]
I close this as stale.
