### ISSUE TITLE
Infinite loop on SQLite error

### ISSUE THREAD

**Issue by gwenn** [stainless-steel/sqlite#86]
The trigger is just a workaround because you cannot use `SELECT RAISE(...)` directly:
```sh
sqlite> SELECT RAISE(FAIL, 'Boom');
Parse error: RAISE() may only be used within a trigger-program
```
```rust
#[test]
fn iter_error_count() {
    let conn = ok!(sqlite::open(":memory:"));
    ok!(conn.execute("CREATE TABLE foo(x)"));
    ok!(conn
        .execute("CREATE TRIGGER oops BEFORE INSERT ON foo BEGIN SELECT RAISE(FAIL, 'Boom'); END"));
    let mut stmt = ok!(conn.prepare("INSERT INTO foo VALUES (0) RETURNING rowid;"));
    let count = stmt.iter().count();
    assert_eq!(count, 0);
}
```
```rust
#[test]
fn iter_error_last() {
    let conn = ok!(sqlite::open(":memory:"));
    ok!(conn.execute("CREATE TABLE foo(x)"));
    ok!(conn
        .execute("CREATE TRIGGER oops BEFORE INSERT ON foo BEGIN SELECT RAISE(FAIL, 'Boom'); END"));
    let mut stmt = ok!(conn.prepare("INSERT INTO foo VALUES (0) RETURNING rowid;"));
    let last = stmt.iter().last();
    assert!(last.is_none());
}
```

**Comment by IvanUkhov** [comment]
Hello, can you please elaborate on what you show with these tests?

**Comment by gwenn** [comment]
https://sqlite.org/c3ref/step.html
> [SQLITE_ERROR](https://sqlite.org/rescode.html#error) means that a run-time error (such as a constraint violation) has occurred. sqlite3_step() should not be called again on the VM.

**Comment by IvanUkhov** [comment]
Added a test here:

https://github.com/stainless-steel/sqlite/blob/main/tests/cursor.rs#L93-L101

Technically, the cursor is an iterator over results. But yeah, having an infinite loop feels uncomfortable.

**Comment by IvanUkhov** [comment]
Made it stop upon exception:

https://github.com/stainless-steel/sqlite/blob/main/tests/cursor.rs#L93-L103

Thank you for reporting!
