### ISSUE TITLE
Will it work with Axum?

### ISSUE THREAD

**Issue by ekanna** [stainless-steel/sqlite#87]
Will it work with Axum which is async web framework https://github.com/tokio-rs/axum ?

Thanks

**Comment by IvanUkhov** [comment]
If you mean whether it is thread safe, it is more a question to SQLite itself:

https://www.sqlite.org/compile.html#threadsafe

Please take a look at this one as well:

https://github.com/stainless-steel/sqlite/blob/main/src/connection.rs#L67
