### ISSUE TITLE
Function Row::try_read() panics if input column does not exist.

### ISSUE THREAD

**Issue by kodeschreiber** [stainless-steel/sqlite#88]
Calling the Row::try_read() function will panic if the input column does not exist. This seems to originate from the "debug_assert" in cursor.rs:
```
impl RowIndex for &str {
    #[inline]
    fn index(self, row: &Row) -> usize {
        debug_assert!(
            row.column_mapping.contains_key(self),
            "the index is out of range",
        );
        row.column_mapping[self]
    }
}
```

Seeing as this function is the more handle-able version of "Row::read", it would be great if this error could be propagated to the try_read for handling. I've only tested this with &str column indexes, but I'm sure the usize variant might be in the same position.

**Comment by kodeschreiber** [comment]
Created [PR90](https://github.com/stainless-steel/sqlite/pull/90) as an option to solve this issue.

**Comment by IvanUkhov** [comment]
I have changed it to return an error if out of range:

https://github.com/stainless-steel/sqlite/commit/e2254c7181a410c7850a40863febc4e4129a2a44
