### ISSUE TITLE
Writing and reading blob data.

### ISSUE THREAD

**Issue by princeb777** [stainless-steel/sqlite#91]
How can i write and read bolb data.

**Comment by IvanUkhov** [comment]
Please take a look at `Value::Binary`:

https://docs.rs/sqlite/latest/sqlite/enum.Value.html#variant.Binary
https://github.com/stainless-steel/sqlite/blob/main/tests/statement.rs#L19
https://github.com/stainless-steel/sqlite/blob/main/tests/statement.rs#L149
