### ISSUE TITLE
Introduce error code constants

### ISSUE THREAD

**Issue by nyovaya** [stainless-steel/sqlite#97]
I think that these error codes should exist as constants to check again errors. https://www.sqlite.org/rescode.html
If appreciated I can provide a PR.

**Comment by IvanUkhov** [comment]
Hello, I think one could simply make this one `pub`:

https://github.com/stainless-steel/sqlite/blob/main/src/lib.rs#L91

And then compare [`Error::code`](https://github.com/stainless-steel/sqlite/blob/main/src/error.rs#L7) like so:

```rust
if matches!(error.code, Some(code) if code == sqlite::ffi::SQLITE3_OK) {
    // …
}
```

**Comment by nyovaya** [comment]
I created a PR for that for now. But I think it would also be useful to put all of the result codes into an enum.

**Comment by IvanUkhov** [comment]
Yeah, one could introduce. Just to make sure it derives comparison traits with `isize` used in `Error::code`.
